#!/usr/bin/env bash
# tools/gen-upstream-baseline.sh — regenerate tools/upstream-baseline.txt
#
# The baseline lists every TRACKED file the refactor does not own, with its content
# hash. Gate A1 in tools/check-newui.sh re-derives it and fails on any drift, so
# "upstream-owned files are untouched" is a measured claim, not a promise.
#
# Re-record only deliberately (`bash tools/gen-upstream-baseline.sh`), and never to
# silence a failure you have not explained.
set -uo pipefail
cd "$(dirname "$0")/.." || exit 1

# On this machine `grep` is shadowed by ripgrep, whose -E means --encoding, so the
# extended-regex usage below would be misparsed. Call the system grep by absolute path.
GREP=/usr/bin/grep

OUT=tools/upstream-baseline.txt

# Paths the refactor owns (new files it is allowed to create and edit). Read from one shared
# pattern file because tools/check-newui.sh gate A1 has to derive the same list to catch a newly
# tracked upstream-owned file that never got baselined — two copies would drift.
IS_OWNED=$(head -n1 tools/upstream-owned.pattern)

tmp=$(mktemp)
git ls-files | "$GREP" -vE "$IS_OWNED" | LC_ALL=C sort > "$tmp"

{
    echo "# Baseline of tracked files the refactor does not own. Generated by"
    echo "# tools/gen-upstream-baseline.sh; verified by tools/check-newui.sh gate A1."
    echo "# Format: <git blob hash><TAB><path>"
    echo "# A tracked path that no longer exists is recorded as '# DELETED<TAB><path>'"
    echo "# so a removal cannot silently disappear from the baseline."
    while IFS= read -r f; do
        if [ -f "$f" ]; then
            printf '%s\t%s\n' "$(git hash-object "$f")" "$f"
        else
            printf '# DELETED\t%s\n' "$f"
        fi
    done < "$tmp"
} > "$OUT"

rm -f "$tmp"
echo "baselined $("$GREP" -c -v -e '^#' -e '^$' "$OUT") tracked file(s)"
echo "recorded deletions: $("$GREP" -c '^# DELETED' "$OUT" || true)"
